In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [2]:
parkinson_df = pd.read_csv("../datasets/parkinsons.csv")
parkinson_df.sample(10)

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
140  phon_R01_S34_1      170.368       268.796        79.543         0.00571   
33   phon_R01_S07_4      202.266       211.604       197.079         0.00180   
19   phon_R01_S05_2      156.405       189.398       142.822         0.00768   
123  phon_R01_S31_2      182.018       197.173        79.187         0.00842   
113  phon_R01_S26_5      210.141       232.706       185.258         0.00534   
137  phon_R01_S33_4      113.166       130.270       100.673         0.00502   
172  phon_R01_S43_2      110.739       113.597       100.139         0.00356   
149  phon_R01_S35_4      202.632       565.740       177.258         0.01627   
161  phon_R01_S39_3      115.322       135.738       107.802         0.00619   
135  phon_R01_S33_2      110.453       127.611       105.554         0.00494   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
140          0.000030   0.00232   0.00269     0.00696       0.03273  ...   
33           0.000009   0.00093   0.00107     0.00278       0.00954  ...   
19           0.000050   0.00372   0.00399     0.01116       0.03995  ...   
123          0.000050   0.00506   0.00449     0.01517       0.02503  ...   
113          0.000030   0.00321   0.00280     0.00964       0.01680  ...   
137          0.000040   0.00257   0.00312     0.00772       0.05279  ...   
172          0.000030   0.00170   0.00200     0.00510       0.01484  ...   
149          0.000080   0.00919   0.00963     0.02756       0.07170  ...   
161          0.000050   0.00352   0.00329     0.01057       0.03273  ...   
135          0.000040   0.00244   0.00315     0.00731       0.04128  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
140      0.05139  0.02485  18.540       1  0.677131  0.685057 -4.796845   
33       0.01407  0.00072  32.684       0  0.368535  0.742133 -7.695734   
19       0.05164  0.03365  17.153       1  0.649554  0.686080 -4.554466   
123      0.04115  0.01813  18.784       1  0.589956  0.732903 -5.445140   
113      0.02583  0.00620  23.671       1  0.441097  0.722254 -5.963040   
137      0.08689  0.03690  16.747       1  0.625362  0.708617 -4.654894   
172      0.02261  0.00430  26.550       0  0.369090  0.776158 -6.085567   
149      0.10546  0.07889  14.989       1  0.427627  0.775708 -4.892495   
161      0.04933  0.02810  19.388       1  0.577802  0.684373 -5.283009   
135      0.06688  0.02529  17.707       1  0.653427  0.706687 -5.333619   

      spread2        D2       PPE  
140  0.397749  2.963799  0.277227  
33   0.178540  1.544609  0.056141  
19   0.340176  2.856676  0.322111  
123  0.142466  2.174306  0.215558  
113  0.250283  2.489191  0.177807  
137  0.304107  2.672362  0.274387  
172  0.192375  1.889002  0.174152  
149  0.262281  2.910213  0.270173  
161  0.226528  2.442906  0.238281  
135  0.322044  2.631793  0.228319  

[10 rows x 24 columns]

In [3]:
parkinson_df.describe()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
count   195.000000    195.000000    195.000000      195.000000   
mean    154.228641    197.104918    116.324631        0.006220   
std      41.390065     91.491548     43.521413        0.004848   
min      88.333000    102.145000     65.476000        0.001680   
25%     117.572000    134.862500     84.291000        0.003460   
50%     148.790000    175.829000    104.315000        0.004940   
75%     182.769000    224.205500    140.018500        0.007365   
max     260.105000    592.030000    239.170000        0.033160   

       MDVP:Jitter(Abs)    MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
count        195.000000  195.000000  195.000000  195.000000    195.000000   
mean           0.000044    0.003306    0.003446    0.009920      0.029709   
std            0.000035    0.002968    0.002759    0.008903      0.018857   
min            0.000007    0.000680    0.000920    0.002040      0.009540   
25%            0.000020    0.001660    0.001860    0.004985      0.016505   
50%            0.000030    0.002500    0.002690    0.007490      0.022970   
75%            0.000060    0.003835    0.003955    0.011505      0.037885   
max            0.000260    0.021440    0.019580    0.064330      0.119080   

       MDVP:Shimmer(dB)  ...  Shimmer:DDA         NHR         HNR      status  \
count        195.000000  ...   195.000000  195.000000  195.000000  195.000000   
mean           0.282251  ...     0.046993    0.024847   21.885974    0.753846   
std            0.194877  ...     0.030459    0.040418    4.425764    0.431878   
min            0.085000  ...     0.013640    0.000650    8.441000    0.000000   
25%            0.148500  ...     0.024735    0.005925   19.198000    1.000000   
50%            0.221000  ...     0.038360    0.011660   22.085000    1.000000   
75%            0.350000  ...     0.060795    0.025640   25.075500    1.000000   
max            1.302000  ...     0.169420    0.314820   33.047000    1.000000   

             RPDE         DFA     spread1     spread2          D2         PPE  
count  195.000000  195.000000  195.000000  195.000000  195.000000  195.000000  
mean     0.498536    0.718099   -5.684397    0.226510    2.381826    0.206552  
std      0.103942    0.055336    1.090208    0.083406    0.382799    0.090119  
min      0.256570    0.574282   -7.964984    0.006274    1.423287    0.044539  
25%      0.421306    0.674758   -6.450096    0.174351    2.099125    0.137451  
50%      0.495954    0.722254   -5.720868    0.218885    2.361532    0.194052  
75%      0.587562    0.761881   -5.046192    0.279234    2.636456    0.252980  
max      0.685151    0.825288   -2.434031    0.450493    3.671155    0.527367  

[8 rows x 23 columns]

In [4]:
parkinson_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [5]:
parkinson_df.drop(columns=["name"],axis=1).corr()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
MDVP:Fo(Hz)          1.000000      0.400985      0.596546       -0.118003   
MDVP:Fhi(Hz)         0.400985      1.000000      0.084951        0.102086   
MDVP:Flo(Hz)         0.596546      0.084951      1.000000       -0.139919   
MDVP:Jitter(%)      -0.118003      0.102086     -0.139919        1.000000   
MDVP:Jitter(Abs)    -0.382027     -0.029198     -0.277815        0.935714   
MDVP:RAP            -0.076194      0.097177     -0.100519        0.990276   
MDVP:PPQ            -0.112165      0.091126     -0.095828        0.974256   
Jitter:DDP          -0.076213      0.097150     -0.100488        0.990276   
MDVP:Shimmer        -0.098374      0.002281     -0.144543        0.769063   
MDVP:Shimmer(dB)    -0.073742      0.043465     -0.119089        0.804289   
Shimmer:APQ3        -0.094717     -0.003743     -0.150747        0.746625   
Shimmer:APQ5        -0.070682     -0.009997     -0.101095        0.725561   
MDVP:APQ            -0.077774      0.004937     -0.107293        0.758255   
Shimmer:DDA         -0.094732     -0.003733     -0.150737        0.746635   
NHR                 -0.021981      0.163766     -0.108670        0.906959   
HNR                  0.059144     -0.024893      0.210851       -0.728165   
status              -0.383535     -0.166136     -0.380200        0.278220   
RPDE                -0.383894     -0.112404     -0.400143        0.360673   
DFA                 -0.446013     -0.343097     -0.050406        0.098572   
spread1             -0.413738     -0.076658     -0.394857        0.693577   
spread2             -0.249450     -0.002954     -0.243829        0.385123   
D2                   0.177980      0.176323     -0.100629        0.433434   
PPE                 -0.372356     -0.069543     -0.340071        0.721543   

                  MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  \
MDVP:Fo(Hz)              -0.382027 -0.076194 -0.112165   -0.076213   
MDVP:Fhi(Hz)             -0.029198  0.097177  0.091126    0.097150   
MDVP:Flo(Hz)             -0.277815 -0.100519 -0.095828   -0.100488   
MDVP:Jitter(%)            0.935714  0.990276  0.974256    0.990276   
MDVP:Jitter(Abs)          1.000000  0.922911  0.897778    0.922913   
MDVP:RAP                  0.922911  1.000000  0.957317    1.000000   
MDVP:PPQ                  0.897778  0.957317  1.000000    0.957319   
Jitter:DDP                0.922913  1.000000  0.957319    1.000000   
MDVP:Shimmer              0.703322  0.759581  0.797826    0.759555   
MDVP:Shimmer(dB)          0.716601  0.790652  0.839239    0.790621   
Shimmer:APQ3              0.697153  0.744912  0.763580    0.744894   
Shimmer:APQ5              0.648961  0.709927  0.786780    0.709907   
MDVP:APQ                  0.648793  0.737455  0.804139    0.737439   
Shimmer:DDA               0.697170  0.744919  0.763592    0.744901   
NHR                       0.834972  0.919521  0.844604    0.919548   
HNR                      -0.656810 -0.721543 -0.731510   -0.721494   
status                    0.338653  0.266668  0.288698    0.266646   
RPDE                      0.441839  0.342140  0.333274    0.342079   
DFA                       0.175036  0.064083  0.196301    0.064026   
spread1                   0.735779  0.648328  0.716489    0.648328   
spread2                   0.388543  0.324407  0.407605    0.324377   
D2                        0.310694  0.426605  0.412524    0.426556   
PPE                       0.748162  0.670999  0.769647    0.671005   

                  MDVP:Shimmer  MDVP:Shimmer(dB)  ...  Shimmer:DDA       NHR  \
MDVP:Fo(Hz)          -0.098374         -0.073742  ...    -0.094732 -0.021981   
MDVP:Fhi(Hz)          0.002281          0.043465  ...    -0.003733  0.163766   
MDVP:Flo(Hz)         -0.144543         -0.119089  ...    -0.150737 -0.108670   
MDVP:Jitter(%)        0.769063          0.804289  ...     0.746635  0.906959   
MDVP:Jitter(Abs)      0.703322          0.716601  ...     0.697170  0.834972   
MDVP:RAP

In [6]:
X = parkinson_df.drop(columns=["name","status"],axis=1)
y = parkinson_df['status']

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=34)

In [16]:
param_grid = {"C":[0.01,0.1,1,10,100]}
lr = GridSearchCV(LogisticRegression(max_iter=10000), param_grid, cv=5, scoring="accuracy", n_jobs= -1,)
lr.fit(X_train,y_train)
prediction = lr.predict(X_test)

#Print results and scores
print(f"Best params : {lr.best_params_} , best score: {lr.best_score_}")
print(f"Accurecy test :{accuracy_score(y_test,prediction)}")
print(f"recall score :{recall_score(y_test,prediction)}")
print(f"Precision score :{precision_score(y_test,prediction)}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test,prediction)}")

#print whole classifiaction report
print(f"This is the full classifiaction report:\n{classification_report(y_test,prediction)}")

Best params : {'C': 100} , best score: 0.839717741935484
Accurecy test :0.8974358974358975
recall score :0.9354838709677419
Precision score :0.9354838709677419
Confusion Matrix:
 [[ 6  2]
 [ 2 29]]
This is the full classifiaction report:
              precision    recall  f1-score   support

           0       0.75      0.75      0.75         8
           1       0.94      0.94      0.94        31

    accuracy                           0.90        39
   macro avg       0.84      0.84      0.84        39
weighted avg       0.90      0.90      0.90        39



In [9]:
param_grid = {
    "max_depth": [3, 5, 10, None], 
    "min_samples_split": [2, 5, 10], 
    "criterion": ["gini", "entropy"]
}

dt = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
dt.fit(X_train, y_train)
prediction = dt.predict(X_test)

# Print results
print(f"Best params: {dt.best_params_} and best score: {dt.best_score_}")
print(f"Test Accuracy: {accuracy_score(y_test, prediction):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, prediction))
print(f"Recall Score: {recall_score(y_test, prediction, average='weighted'):.4f}")
print(f"Precision Score: {precision_score(y_test, prediction, average='weighted'):.4f}")
print("Classification Report:\n", classification_report(y_test, prediction))

Best params: {'criterion': 'entropy', 'max_depth': None, 'min_samples_split': 5} and best score: 0.8721774193548386
Test Accuracy: 0.8974
Confusion Matrix:
 [[ 6  2]
 [ 2 29]]
Recall Score: 0.8974
Precision Score: 0.8974
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.75      0.75         8
           1       0.94      0.94      0.94        31

    accuracy                           0.90        39
   macro avg       0.84      0.84      0.84        39
weighted avg       0.90      0.90      0.90        39



In [10]:
param_grid = {
    "n_estimators": [50, 100, 200], 
    "max_depth": [5, 10, 20], 
    "min_samples_split": [2, 5]
}

rf = GridSearchCV(RandomForestClassifier(class_weight="balanced"), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
rf.fit(X_train, y_train)
prediction = rf.predict(X_test)

# Print results
print(f"Best params: {rf.best_params_} and best score: {rf.best_score_}")
print(f"Test Accuracy: {accuracy_score(y_test, prediction):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, prediction))
print(f"Recall Score: {recall_score(y_test, prediction, average='weighted'):.4f}")
print(f"Precision Score: {precision_score(y_test, prediction, average='weighted'):.4f}")
print("Classification Report:\n", classification_report(y_test, prediction))

Best params: {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100} and best score: 0.8981854838709677
Test Accuracy: 0.9231
Confusion Matrix:
 [[ 5  3]
 [ 0 31]]
Recall Score: 0.9231
Precision Score: 0.9299
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.62      0.77         8
           1       0.91      1.00      0.95        31

    accuracy                           0.92        39
   macro avg       0.96      0.81      0.86        39
weighted avg       0.93      0.92      0.92        39



In [11]:
model = SVC(kernel='linear', class_weight='balanced')

model.fit(X_train,y_train)
prediction = model.predict(X_test)

print(f"Test Accuracy: {accuracy_score(y_test, prediction):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, prediction))
print(f"Recall Score: {recall_score(y_test, prediction, average='weighted'):.4f}")
print(f"Precision Score: {precision_score(y_test, prediction, average='weighted'):.4f}")
print("Classification Report:\n", classification_report(y_test, prediction))

Test Accuracy: 0.8462
Confusion Matrix:
 [[ 6  2]
 [ 4 27]]
Recall Score: 0.8462
Precision Score: 0.8631
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.75      0.67         8
           1       0.93      0.87      0.90        31

    accuracy                           0.85        39
   macro avg       0.77      0.81      0.78        39
weighted avg       0.86      0.85      0.85        39



In [12]:
param_grid = {
    "n_neighbors": [3, 5, 7, 9, 11],  
    "weights": ["uniform", "distance"],  
    "metric": ["euclidean", "manhattan", "minkowski"]  
}


knn = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
knn.fit(X_train, y_train)  # Train KNN on scaled data

# Predict on test data
prediction = knn.predict(X_test)

# Print results
print(f"Best params: {knn.best_params_} and best score: {knn.best_score_}")
print(f"Test Accuracy: {accuracy_score(y_test, prediction):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, prediction))
print(f"Recall Score: {recall_score(y_test, prediction, average='weighted'):.4f}")
print(f"Precision Score: {precision_score(y_test, prediction, average='weighted'):.4f}")
print("Classification Report:\n", classification_report(y_test, prediction))

Best params: {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'uniform'} and best score: 0.8655241935483872
Test Accuracy: 0.7949
Confusion Matrix:
 [[ 4  4]
 [ 4 27]]
Recall Score: 0.7949
Precision Score: 0.7949
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.50      0.50         8
           1       0.87      0.87      0.87        31

    accuracy                           0.79        39
   macro avg       0.69      0.69      0.69        39
weighted avg       0.79      0.79      0.79        39



In [13]:
import pickle
filename = "parkinson_model"
pickle.dump(rf.best_estimator_,open(filename,'wb'))